### ISSUE TITLE
BrowserSelect crashes when 3CXPhone for Windows is installed

### ISSUE THREAD

**Issue by ximmox** [zumoshi/BrowserSelect#21]
Hello there, 

we are facing a very strange issue when using BrowserSelect 1.3.4 (which I am using to separate between IE for our ERP and Firefox for everything else) and the 3CXPhone (VOIP-Softphone-Client, see www.3cx.com), which we intend to roll out in Q1 of 2017 in our company.

As soon as either v14 ([Link to v14](http://downloads.3cx.com/downloads/3CXPhoneforWindows14.msi)) or v15 ([Link to v15](http://downloads.3cx.com/downloads/3CXPhoneforWindows15.msi)) of the 3CX client are installed, then BrowserSelect crashes immediately upon start.

There are two errors in the Windows errorlog, this happens on Windows 7:

Application error:
```
Name der fehlerhaften Anwendung: BrowserSelect.exe, Version: 1.3.4.0, Zeitstempel: 0x57c938b6
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 6.1.7601.23539, Zeitstempel: 0x57c99bd4
Ausnahmecode: 0xe0434352
Fehleroffset: 0x000000000001a06d
ID des fehlerhaften Prozesses: 0x16ac
Startzeit der fehlerhaften Anwendung: 0x01d256baf658bc78
Pfad der fehlerhaften Anwendung: C:\Users\*REDACTED*\AppData\Local\BrowserSelect\BrowserSelect.exe
Pfad des fehlerhaften Moduls: C:\Windows\system32\KERNELBASE.dll
Berichtskennung: 3540c629-c2ae-11e6-bde0-989096ced834

Detailview:
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2016-12-15T10:06:55.000000000Z" /> 
  <EventRecordID>141717</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>*REDACTED*</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>BrowserSelect.exe</Data> 
  <Data>1.3.4.0</Data> 
  <Data>57c938b6</Data> 
  <Data>KERNELBASE.dll</Data> 
  <Data>6.1.7601.23539</Data> 
  <Data>57c99bd4</Data> 
  <Data>e0434352</Data> 
  <Data>000000000001a06d</Data> 
  <Data>16ac</Data> 
  <Data>01d256baf658bc78</Data> 
  <Data>C:\Users\*REDACTED*\AppData\Local\BrowserSelect\BrowserSelect.exe</Data> 
  <Data>C:\Windows\system32\KERNELBASE.dll</Data> 
  <Data>3540c629-c2ae-11e6-bde0-989096ced834</Data> 
  </EventData>
  </Event>
```

.NET Runtime Error:
```
Anwendung: BrowserSelect.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.ArgumentException
   bei System.IO.Path.CheckInvalidPathChars(System.String, Boolean)
   bei System.IO.Path.GetFileName(System.String)
   bei BrowserSelect.BrowserFinder+<>c.<find>b__0_0(BrowserSelect.Browser)
   bei System.Linq.Enumerable+WhereListIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   bei System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.Collections.Generic.IEnumerable`1<System.__Canon>)
   bei System.Linq.Enumerable.ToList[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
   bei BrowserSelect.BrowserFinder.find()
   bei BrowserSelect.Form1..ctor()
   bei BrowserSelect.Program.Main(System.String[])

Detailview:
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1026</EventID> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2016-12-15T10:06:54.000000000Z" /> 
  <EventRecordID>141716</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>WS-ih.jueke.local</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>[...see above...]</Data> 
  </EventData>
  </Event>
```

I suppose the easiest way to debug is installing the 3CX client yourself, but I am willing to add any information you might need.

As soon as the client is uninstalled, BrowserSelect works again as it did all previous months.

Thanks for this great little tool & I hope you can find where the issue might come from.

Regards from Germany, 
immo

**Comment by zumoshi** [comment]
Hello,
thank you for your report. this issue is similar to #17.
upon installation, 3cx adds a key to `StartMenuInternet` key in the registry, however, since it can't handle the HTTP protocol browserSelect cannot understand it and fails to create the list of browsers.

the last version of browser select is more tolerant to incompatible/incomplete keys when parsing registry. I will release it as an official version after some more testing soon. but you can verify that your problem is solved by trying the attached pre-release executable.

[BrowserSelect-1.3.5.pre-release.zip](https://github.com/zumoshi/BrowserSelect/files/656517/BrowserSelect-1.3.5.pre-release.zip)

**Comment by ximmox** [comment]
Hello, 

Thanks for the quick reply, the pre-release version 1.3.5 fixes the issue described here and lets BrowserSelect and 3CXPhone work side by side.
The only downside: I am missing the IE-entry in BrowserSelect now, I can only see Firefox and Chrome. 
The registry key you provided in #17  doesn't make a difference, after applying it IE is still not selectable.
(I am using IE v11.0.9600.18376IS if that might be of interest).

Any other idea how to add IE back in?

**Comment by zumoshi** [comment]
yes, that would bring IE back. the previous versions of browserSelect did not check the capabilities key and just assumed all entries in startMenuInternet can handle `HTTP`. which was not right since 3cx also adds itself to the startMenuInternet yet can't handle `HTTP`.

is IE missing capabilities by default? if that is the case I should add an exception for it so it won't be ignored.

**Comment by ximmox** [comment]
Sorry for editing my post after you already replied.

For me it works with the workaround described above, but If you hardcoded an exeption for IE (which should be on most of the machines running windows) then manually adding registry entries wouldn't be necessary.

**Comment by zumoshi** [comment]
I was under impression that IE has a capabilities key by default. I've added an exception for it.
you can get the last version from [here](https://github.com/zumoshi/BrowserSelect/releases/download/1.3.5/BrowserSelect.exe).

**Comment by ximmox** [comment]
I deleted my manual Capatibilites entries and it works now with only your IE-registry file from #17 and your latest version (1.3.5).

Thanks, problem solved in recordspeed! :)
